<Project>
  <PropertyGroup>
    <Version>1.0.0</Version>
    <Authors>smouj</Authors>
    <Product>AreaSnap</Product>
    <RepositoryUrl>https://github.com/smouj/areasnap</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>